---
title: Performance of individual audit filters in predicting opportunities for improvement
  in adult trauma patients
author: "Josef Al-Khalili"
subtitle: A registry based cohort study
output:
  pdf_document: default
  word_document: default
  html_document: 
    df_print: paged
csl: bmcemerg.csl
editor_options:
  markdown:
    wrap: 72
bibliography: bibliography.bib
---

# Abbreviations
OFI – Opportunities For Improvement
AF – Audit filter
CI – confidence interval
GCS – Glascow Coma Scale
ISS – Injury Severity Score
ED – Emergency Department
AUC – Area Under Curve
ROC – Reciever Operating Characteristic
CPR – Cardiopulmonary Resuscitation
SBP – Systolic Blood Pressure
WHO – World Health Organisation
YLL – Years Life Lost
DALY – Disability Adjusted Life Years
PTSD – Post Traumatic Stress Disorder 

# Introduction

Trauma is defined as a physical injury of external origin together with the associated reaction of the body. This phenomenon accounts for 9% of global deaths annually [@world2014injuries]. Trauma affects low- and middle-income countries at a higher rate. In addition, young people are at higher risk of trauma compared to the general population. It is the leading cause of death in people between the ages of 10 and 49 [@vos2020global];[@roth2018global]. The most common type of trauma for people of all ages is road traffic injuries
[@vos2020global];[@roth2018global]. In Sweden, road traffic injuries account for about 40% of injuries and falls for 40%
[@SweTrau2022Arsrapport].

Trauma is broadly divided into two groups according to the underlying causal mechanism: penetrating and blunt trauma. Common examples of penetrating trauma are gunshot wounds and knife cuts. Blunt trauma, on the other hand, is caused by injuries such as road traffic accidents and falls. In general, the two types of trauma can also be characterized by the size of the force causing the injury and the area of impact. Blunt trauma is caused by a high force impact over a larger area. In contrast, penetrating trauma is caused by a force applied to a smaller area, causing greater pressure so that it is penetrating and often results in deeper lacerations to tissues and organs. However, blunt trauma with sufficient force can be penetrating in nature [@hexdall2011Mechanism].

## Impact

The effects of a trauma depend greatly on the type of trauma, where it happened and whom it affected.

Trauma is responsible for 11.9% of years of life lost (YLL) worldwide
[@roth2018global]. In addition, trauma is associated with a higher propensity for depression, post-traumatic stress disorder (PTSD) and negative effects on cognitive function, etc.
[@north1999psychological];[@muscatelli2017prevalence].

It is estimated that up to 11% of trauma patients have PTSD 3 years after the traumatic event [@visser2017course]. In addition, people who witness traumatic injuries are also at a higher risk of developing PTSD.\
Traumatic injuries are associated with 36% not returning to work within 1 year [@david2022measuring].

However, injuries are not only a burden on the person affected, but also on society as a whole [@newnam2014impacts]. One aspect of such societal impact is the economic cost. Attempts have been made to estimate the global cost of injuries, which is a complicated task due to their variability. However, it is estimated that the cost of road traffic injuries alone accounts for 2% of gross domestic product (GDP) in high-income countries [@world2014injuries].

## Trauma Care Systems

Trauma care is a multidisciplinary, complex and time-critical healthcare service provided by specialised trauma centres. A variety of different specialties are involved in trauma care, including surgeons, orthopedists, anesthesiologists, emergency physicians and nurses. Trauma care is divided into three components: pre-hospital, in-hospital and post-hospital. The prehospital component is trauma centres have a significantly lower mortality rate compared to non-trauma centres.
And the maturity of a trauma centre also correlates with lower mortality, demonstrating the importance of high-quality, specialised trauma care
[@alharbi2021effectiveness];[@mann1999systematic]. A similar study in
Sweden [@candefjord2020mortality] showed that 30-day mortality is 41% lower in a mature trauma centre compared to a non-trauma centre. However, \
even in established trauma care systems, it is prone to error due to its complexity and susceptibility to delays
[@nikouline2021errors];[@vioque2014classifying], which in turn can lead to complications and death. Studies between 1990 and 2014 have shown a pooled preventable death rate of 20%, with more recent studies showing less
[@kwon2014pooled]. A recent study in a Swedish Level I trauma centre found a preventable death rate of 4% [@ghorbani2018analysis].

## Quality Improvement

To minimize errors in trauma care, quality improvement (QI) programs have been established by the World Health Organization (WHO)
programs by the World Health Organization (WHO) and the International
International Association for Trauma Surgery and Intensive Care (IATSIC)
[@world2009guidelines]. These programs form the core of current trauma care systems and their development around the world.

QI programs consist of a series of recommended techniques aimed at facilitating discussion and analysis of the trauma process in order to take corrective action for future success. The following techniques are
used: A multidisciplinary mortality and morbidity conference (MMC), a preventable death review panel, and the use of audit filters[@world2009guidelines].

### Morbidity and Mortality Conferences and Preventable Death Review Panels
The MMC is a central QI technique. It is a proven framework with the critical components of anonymity, focusing on specific adverse events, recognising flawed approaches, critical analysis, seeking
 change and implementing that change [@gregor2016morbidity].

MMCs are regular meetings at which specific patient cases are presented for discussion. The conference participants are healthcare professionals involved in trauma care and its processes, but not necessarily the specific patient case. The selection of patient cases varies, but common themes for discussion are unexpected mortality, unexpected morbidity and errors [@orlander2003morbidity].

It is recommended that they last about 40 minutes, but this varies from hospital to hospital [@world2009guidelines].

Five themes have been proposed that broadly define QI-centred MMC: (1)
clear definition of the role of the MMC (2), involvement of stakeholders, (3)
recognising and selecting appropriate patient cases for presentation, (4)
structuring focused discussions, and (5) formulating recommendations and assigning follow-up actions[@giesbrecht2016morbidity];[@churchill2020quality].

When implemented effectively, MMCs serve as an important tool for error proofing without serving solely as a negative for individual care providers, but rather as an incentive for reporting. These conferences promote a more comprehensive, systems-based approach that emphasizes task analysis, teamwork and quality improvement[@lazzara2022morbidity]. The introduction of MMC has been shown to increase morbidity and mortality reporting[@kong2016analysis].

Following MMC, there is an avoidable death review panel whose role is to determine whether a patient's death could have been avoided [@ghorbani2014clinical].
### Audit filters and Opportunities for improvement

Audit filters also known as quality indicators are specific established
criteria involved in trauma processes and care. It is used to detect
deviation from standardized care in order to further analyse the cause
behind complications in trauma patients. An audit filters can be death
and the placement of 2 large bore intravenous lines within 15 minutes
from arrival to a healthcare facility [@world2009guidelines]. The
purpose of audit filters is to improve quality of care.

Earlier studies showed a reduction in trauma related mortality after the
implementation of audit filters [@chadbunchachai2001comparative].
However, newer studies seem to differ. In 2009 there was an extensive
review made that sought to determine if audit filters could be used in
improving processes of trauma care however none of the studies met
established inclusion criteria [@evans2009audit]. The use of audit
filters have also been associated with high frequencies of false
positives, ranging from 24% to 80%.[@sanddal2011analysis];
[@roy2017learning].

OFIs are the endpoint and aim of MMC. Following the review of individual
patient cases there is a consensus decision made regarding the existence
of an OFI. It has been shown that such review process is associated with
high-quality trauma care [@santana2014development]. OFIs are typically
associated with failures in initial care [@vioque2014classifying],
specifically in airway management, fluid resuscitation, haemorrhage
control and chest injury management [@sanddal2011analysis];
[@roy2017learning]; [@o2013opportunities]. Some audit filters seem to
not correlate with OFIs at all [@lewis2017delay]

## Aim

The aim of the study is to determine whether audit filters are good
indicators for predicting OFIs.

# Methods

We conducted a registry-based cohort study which uses data from the
trauma registry and trauma care quality database at the Karolinska
University hospital in Solna in order to evaluate the performance of
individual audit filters in predicting OFIs.

## Study setting and population

Karolinska University Hospital is classified as a Trauma level I
hospital. Every year around 1500 patients receive treatment at the
hospital. If a patient case results in team activation it is added to
the Karolinska trauma registry. If no team activation occurred but the
patient had ISS\>9 retrospectively it is also included in the registry.
The Karolinska trauma registry reports to the Swedish Trauma registry
(SweTrau). The registry includes data on vital signs, times, injuries,
and interventions as well as patient demographics according to the
European consensus statement, the Utstein template

The Karolinska trauma registry also contains a care quality database
including specific audit filters and OFIs that are determined in MMC
conferences through consensus decision.

This process of determining OFIs unfolds in multiple stages,
characterized by escalating levels of scrutiny. Notably, instances of
mortality are directly referred to the multidisciplinary conference,
where, in addition to assessing OFIs, a determination is made regarding
whether the death was preventable or potentially preventable, a
classification also falling under the purview of OFIs.

From 2013 to 2017 there was an effort put forward in identifying adverse
outcomes which where unrelated to mortality, the review process
underwent subsequent refinement and formalization during the study
period. During the initial period each trauma patient case underwent
individual assessments by a specialized trauma nurse in order to
identify potential OFIs. It was, however not until 2017 in which this
procedure was formalized and it became standardized to incorporate a
preliminary individual evaluation by a specialized trauma nurse upon
data registration in the trauma registry and the trauma quality
database. The trauma quality data underwent screening of audit filters.
All cases falling within the criteria delineated by these filters, along
with those trauma patients flagged by the nurse during the initial
review for possible care failures, were subjected to a secondary review
by two specialized nurses. Subsequent identification of a potential OFI
during this second review prompted a comprehensive evaluation of the
respective trauma patient's case.

## Participants

In this study, we included all who underwent screening for OFIs.
Exclusion criteria were applied to individuals under the age of 15, as
their clinical management process has notable distinctions compared to
those applicable to the adult population.

## Variables

### Outcome

The outcome variable in this study is an OFI, as established by the MMC
conference through unanimous decision and furthermore valued as a binary
variable with "Yes - At least one OFI identified" and "No - No OFI
identified".

### Exposures

The exposure variable is the 10 audit filters used at Karolinska university hospital.

## Data sources/measurement
Data for this cohort were retrieved from the trauma registry and the trauma care quality database during the period spanning from 2012 to 2022. 

The individual audit filters, was identified through the trauma registry

The OFIs was extracted from the trauma care quality database

All data were anonymized to protect patient privacy.
## Bias

Selection bias since the outcome of this study has already occurred.\
There is a possibility that consensus decisions from the MMC conferences
are flawed which causes misclassification bias. Furthermore, the process of flagging a patient case with an audit filter is done manually by a specialised nurse as mentioned above. This means that there may be a selection bias

Recall bias. Individuals who attend the MMC and has also been a witness to the speific patient case in question might not remember certain key elements that might affect the decision.


## Study size

The study cohort encompasses all eligible patients treated at the
hospital from 2012 to 2022. There were only two patient cases from 2012.

## Statistical methods

The study results are generated by statistical analytics methods with
the help of the statistical programming language, R. [@R2022language]

To calculate the sensitivity and specificity of each individual audit
filter in predicting an OFI a mathematical equation is used:

The sensitivity is calculated accordingly: True positives / (true
positives + false negatives)

The specificity is calculated accordingly: True negatives / (true
negatives + false positives)

A receiver operating curve (ROC) will be made and the area under the curve (AUC) calculated in order to compare the performance of each audit filter [@robin2011proc]

Using a bootstrapping method with 1000 iterations of the selected data, a 95% confidence interval for sensitivity, specificity and AUC will be calculated. Furthermore, comparing AUC of each audit filter with that of coincidence (AUC = 0.5) through a one sample T test will be done to determine significance. This applies soley to any audit filter that might have an AUC confidence interval spanning 0.5.

# Results
## 1 Participants
### 1.2 Study Participants and Setting

In this retrospective cohort, a total of 8312 trauma care cases were assessed. The study was conducted at Karolinska University Hospital, which is a level I trauma center specializing in trauma care.

### 1.3 Participant Characteristics

Table 1 presents the baseline characteristics of the study participants.After excluding patients under 15 years old and patients not screened for OFI, a total of 8309 individuals where admitted to the hospital and also screened for an OFI. A total of 7797 of the screened individuals had no OFI and 512 had an OFI.
69% out of all patients included in the study where men and 31% where women. 

Among the 512 patients with an OFI compared to the 7797 patients without, the mean age was slightly higher (mean 49 vs 42 years old) and the ISS was higher (mean 17 vs 9). The number of intubations was also higher (16% vs 8,3%).
Patients with OFI had longer times to definitive treatment compared to patients without OFI (median: 144 vs 102 minutes from hospital arrival). Furthermore the time to first CT was also longer in the group with OFI compared to the group without OFI (39 min vs 33 min). 

The mean systolic blood pressure in the OFI group did not differ from the systolic blood pressure in the no OFI group. 

The variables with the highest amount of missing data was "time to definitive treatment" [n=5990] and "time to first CT" [n=1012].

## 2. Individual Audit Filters
###2.1. Performance of Individual Audit Filters

Table 2 summarizes the performance of each individual audit filter in identifying opportunities for improvement in trauma care.

There where varying amounts of patient cases flagged with each audit filter. The audit filter that was flagged most frequently was ">30 min until CT". The least flagged audit filter was "GCS<9 and not intubated".

The audit filter with the highest specificity was "GCS<9 and not intubated" (98.7% CI: 98.5-98.9) was also the auditfilter with the lowest sensitivity (1.2% CI: 0.1-2).

The audit filter with the highest sensitivity was ">30min until CT" (59.2% Ci: 55.3-63.3). The same audit filter had the lowest specificity (53.8% CI: 52.7-55.2).

The confidence intervals varied between sensitivity and specificity with sensitivity having greater span.

three of the ten audit filters, "Dead at 30 days", "GCS<9 and not intubated" and "CPR and thoracotomy" showed a performance in predicting an OFI equal to that of coincidence. >60 min until first intervention had the highest AUC.

10. Limitations
10.1. Limitations

We acknowledge several limitations in our study, including [enumerate the study limitations, e.g., potential selection bias, data quality, and generalizability]. These limitations should be considered when interpreting the results.
# Discussion
##  Interpretation of Results 
The aim of the study was to determine the performance of individual audit filters in predicting OFI in order to assess wether they should be used as screening method for OFI or not.

Male admission to trauma centres outnumbered females with almost double. This is similar to other studies.

Earlier review articles sought to review the evidence for audit filters found no evidence supporting the use of audit filters in improving trauma care [@evans2009audit]. This shows that even though audit filters are wildly used there is not much support for the use of it.

The audit filters that did not prove to be better than randomness   suggest that their use as a screening method for determining OFI is not valuable and should not be used for that purpose.

in a 2008 study by Willis [@willis2008interpreting] they look at the individual risk for poor outcome in 14 audit filters. Out of these 14 audit filters only three audit filters showed an increased risk for poor outcome while the rest showd no significant ability to predict poor outcome. One audit filter, GCS<9 and not intubated, which was used by Willis is also used at the trauma center at Karolinska University Hospital. Similarly the audit filter showed no significant ability to predict poor outcome.     

Some of the audit filters, however, showed promising results in predicting OFI. 

The possible reason behind the audit filters having a high specificity relative to their sensitivity may be due to the outcome being rather uncommon whilst every individual audit filter miss the majority of OFI. Theoretically, adding all audit filters together would result in the sensitivity increasing. 

Both audit filters measuring delay (>60 until first intervention and >30min until CT) showed promising results in predicting opportunities for improvement which could be explained by the fact that delay have shown to correlate with increased risk for adverse outcomes like preventable death [@teixeira2007preventable]. An injured individual might be standing on a thin line between survival and death if the adequate intervetion does not occur in time. This makes delay in general a good predictor of outcome. 

The reason behind the fact that audit filter 1 showed no difference from randomness could be because severe traumatic injuries might inevitably die within 30 days of admission to the hospital resulting in no consensus on the existence of an OFI in such particular case.

A similar explanation can be done with audit filter 9 which also showed a insignificant performance in predicting OFI. CPR and thoracotomy generally has a very low survival rate and might only be done to those who are severely injured.



##Generalizability
Since the screening method for identifying an OFI may vary at different trauma centres there will be a difference in results. 

The audit filters being used differ between trauma centrer which adds to the difficulty of creating a standard screening system.
##Limitations
Opportunity for improvement, while defined as a binary variable, includes a diverse set of
outcomes ranging from preventable deaths to bad documentation. This makes it difficult to create audit filters that do well in predicting an OFI.

The current screening system for OFI might also introduce bias since the filters would favour the
identification of some, but not all, errors

Future research should focus on identifying potential subgroups of OFI
that proves to be relatively hard to predict and adjust accordingly.
 

The way the audit filters performance were individually calculated, as stated in the method section, was to look at every patientcase with or without an OFI and silmuntaniously flagged or not flagged with the audit filter. THis means that even tho an audit filter presented a true positive correlation with an OFI, there is still a chance, if the same patient case had more than one audit filter flagged, that it was not the tested audit filter that predicted truthfully rather it was the other audit filter.


This further strengthens the idea that OFI should be divided in subgroups in order to better asses the performance of each audit filters with the corresponding OFI subgroup.
##Health Equity 
#Conclusion
#Tables
```{r Table1, echo=FALSE, fig.cap=" IN_CAPTION", fig.align="center", warning=FALSE, message=FALSE,error=FALSE}
source("main.R")
library(rofi)
library(dplyr)
library(ggplot2)
library(pROC)
library(gtsummary)
library(gt)
library(boot)

tableOne

```
# References

::: {#refs}
:::

#Appendices
